export const SET_USER_PATH = 'SET_USER_PATH';
export const RESET_USER_PATH = 'RESET_USER_PATH';
export const FETCH_NIVEL_STATS = 'FETCH_NIVEL_STATS';
export const UPDATE_NIVEL_STATS = 'UPDATE_NIVEL_STATS';
export const UPDATE_USER_NIVEL_STATS = 'UPDATE_USER_NIVEL_STATS';
